import {
  EmailIcon,
  EmailShareButton,
  FacebookIcon,
  FacebookShareButton,
  GabIcon,
  GabShareButton,
  HatenaIcon,
  HatenaShareButton,
  InstapaperIcon,
  InstapaperShareButton,
  LineIcon,
  LineShareButton,
  LinkedinIcon,
  LinkedinShareButton,
  MailruIcon,
  MailruShareButton,
  OKIcon,
  OKShareButton,
  PocketIcon,
  PocketShareButton,
  RedditIcon,
  RedditShareButton,
  TelegramIcon,
  TelegramShareButton,
  TumblrIcon,
  TumblrShareButton,
  TwitterIcon,
  TwitterShareButton,
  ViberIcon,
  ViberShareButton,
  VKIcon,
  VKShareButton,
  WeiboIcon,
  WeiboShareButton,
  WhatsappIcon,
  WhatsappShareButton,
  WorkplaceIcon,
  WorkplaceShareButton
} from 'react-share'

const title = 'Adsme'

export const shareButtonConfig = [
  { Button: FacebookShareButton, Icon: FacebookIcon },
  { Button: TwitterShareButton, Icon: TwitterIcon, props: { title } },
  { Button: TelegramShareButton, Icon: TelegramIcon, props: { title } },
  { Button: WhatsappShareButton, Icon: WhatsappIcon, props: { title, separator: ':: ' } },
  { Button: LinkedinShareButton, Icon: LinkedinIcon },
  { Button: VKShareButton, Icon: VKIcon },
  { Button: OKShareButton, Icon: OKIcon },
  { Button: RedditShareButton, Icon: RedditIcon, props: { title, windowWidth: 660, windowHeight: 460 } },
  { Button: GabShareButton, Icon: GabIcon, props: { title, windowWidth: 660, windowHeight: 640 } },
  { Button: TumblrShareButton, Icon: TumblrIcon, props: { title } },
  { Button: MailruShareButton, Icon: MailruIcon, props: { title } },
  { Button: EmailShareButton, Icon: EmailIcon, props: { subject: title, body: 'body' } },
  { Button: ViberShareButton, Icon: ViberIcon, props: { title } },
  { Button: WorkplaceShareButton, Icon: WorkplaceIcon, props: { quote: title } },
  { Button: LineShareButton, Icon: LineIcon, props: { title } },
  { Button: WeiboShareButton, Icon: WeiboIcon, props: { title } },
  { Button: PocketShareButton, Icon: PocketIcon, props: { title } },
  { Button: InstapaperShareButton, Icon: InstapaperIcon, props: { title } },
  { Button: HatenaShareButton, Icon: HatenaIcon, props: { title, windowWidth: 660, windowHeight: 460 } }
]
