export const USER_LOCALE_STORAGE_KEY = 'user_storage_key'
export const USER_TOKEN_LOCALE_STORAGE_KEY = 'user_token_storage_key'
export const USER_PHONE_LOCALE_STORAGE_KEY = 'user_phone_storage_key'
export const USER_RADIUS_LOCALE_STORAGE_KEY = 'user_radius_storage_key'
export const USER_SUBSCRIPTION_LOCALE_STORAGE_KEY = 'user_subscription_storage_key'
